dtolnay/trybuild

src/dependencies.rs, src/env.rs, src/error.rs, src/lib.rs, src/manifest.rs, src/run.rs
While working on https://github.com/dtolnay/trybuild/pull/17 I occasionally needed to peek into the contents of the manifest structs being modified by trybuild. The current lack of `#[derive(debug)]` made this rather cumbersome at times.
=> Added `#[derive(Debug)]` for easier inspection of manifest structs, etc

src/cargo.rs, src/dependencies.rs, src/manifest.rs, src/run.rs
This PR adds support for `[patch]` and `[replace]` directives in both member and workspace manifests, according to [The Manifest Format](https://doc.rust-lang.org/cargo/reference/manifest.html#the-workspace-section) (emphasis mine):
> Workspaces were added to Cargo as part of RFC 1525 and have a number of properties:
> 
> - A workspace can contain multiple crates where one of them is the root crate.
> - The root crate's Cargo.toml contains the [workspace] table, but is not required to have other configuration.
> - Whenever any crate in the workspace is compiled, output is placed in the workspace root (i.e., next to the root crate's Cargo.toml).
> - The lock file for all crates in the workspace resides in the workspace root.
> - **The [patch], [replace] and [profile.*] sections in …
=> Support for [patch] & [replace] directives in member & workspace manifests

src/lib.rs, src/run.rs
After expand_globs Runner's new drain_filter method removes tests if a 3rd argument with trybuild= is included.  If no matches are found no tests run and the appropriate message is printed. I added an include field to the Runner struct which is the env::args(). Any suggestions I'm happy to change.
=> Ignore test

src/run.rs
Fixes #28. Example message:
```console
error[E0277]: the trait bound `f64: std::convert::From<&str>` is not satisfied
--> $DIR/test.rs:2:5
|
2 |     b::f("");
|     ^^^^ the trait `std::convert::From<&str>` is not implemented for `f64`
|
::: $WORKSPACE/b/src/lib.rs:1:13
|
1 | pub fn f<T: Into<f64>>(_: T) {}
|             --------- required by this bound in `b::f`
|
= help: the following implementations were found:
<f64 as std::convert::From<f32>>
<f64 as std::convert::From<i16>>
<f64 as std::convert::From<i32>>
<f64 as std::convert::From<i8>>
and 3 others
= note: required because of the requirements on the impl of `std::convert::Into<f64>` for `&str`
```
=> Normalize workspace-relative paths

src/normalize.rs
Fixes #30. All lines beginning with `"::: "` have their paths normalized to use Unix path separators, and the `$WORKSPACE` normalization takes this into account.
=> Normalize separators in $WORKSPACE paths

Cargo.toml
---
Is it worth trying to find the actual minimum version of `serde` for `toml-rs`? See alexcrichton/toml-rs@381d020563ac3c1421c77cd5799a4b78462767b7 for details on that change.
=> Dependency cleanup

Cargo.toml, src/diff.rs, src/lib.rs, src/message.rs
Requires an opt-in for now (`cargo test --features trybuild/diff`).
Currently unix-only. We will need to look into how to get highlighted background color reliably on Windows terminals, and ideally implement support for it in https://github.com/BurntSushi/termcolor.
The diff is backed by https://github.com/dtolnay/dissimilar which is intended to produce human readable diffs with less noise than raw Myers' algorithm.
The intended output looks like:
<p align="center"><img src="https://user-images.githubusercontent.com/1940490/71450848-e365b700-2737-11ea-9656-116ef72c01b9.png" width="80%"></p>
Tracking issue: #41
Closes #25. Closes #26. Closes #27.
=> Highlight diffs

src/rustflags.rs
This allows build scripts (via `cfg!(trybuild)`) and libraries (via `#[cfg(trybuild)]`) to omit parts that are unneeded for the ui tests.
=> Define cfg(trybuild) when compiling

src/message.rs
=> Add TRYBUILD=overwrite mention to error messages

src/cargo.rs
The instance of cargo that is launched by trybuild always has a subset of the dependencies of the current test run, meaning the should already be in cargo's cache.
Resolves #50.
=> Always execute cargo with the --offline flag

src/cargo.rs
Rel #53.
Runs [`cargo generate-lockfile`](https://doc.rust-lang.org/cargo/commands/cargo-generate-lockfile.html) before building the generated `trybuild` runner crate.
It is run with `--offline` so forces resolutions of locally available dependencies, which should be the same set of dependencies resolved and downloaded for the outer crate.
=> Force lockfile regeneration

src/cargo.rs
I don't know whether leaving this out was an oversight or not, but it is
definitely required for my use case (my crate doesn't build without one
of a set of features being passed). I also can't see a reason why the
features shouldn't be passed here.
=> Pass features when building dependencies

src/normalize.rs
Some rustc errors contain trailing whitespace on lines. This is probably a bug but we might as well work around it.
Trailing whitespace in stderr files is problematic because some editors will throw it away on save.
=> Keep trailing whitespace out of stderr files

src/normalize.rs, tests/test.rs, tests/ui/compile-fail-3.rs, tests/ui/compile-fail-3.stderr
Rust anonymous closure types include the path to the position in the file where the closure was defined. This results in different output on windows compared to linux and mac. This patch looks for lines starting with "= note: required because it appears within the type", and replaces all '\' with '/' in order to be cross platform.
I'm not completely confident about how we're supposed to order the different normalization schemes, but this placement seems to work in my local testing.
=> normalize dir seperators in types

src/normalize.rs, src/tests.rs
Closes #83.
Before:
```console
error[E0277]: the trait bound `Ret: serde::ser::Serialize` is not satisfied
--> $DIR/bad_endpoint6.rs:22:8
|
22  |     Ok(HttpResponseOkObject(Ret { "Oxide".to_string(), 0x1de }))
|        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `serde::ser::Serialize` is not implemented for `Ret`
|
::: $WORKSPACE/dropshot/src/handler.rs:846:21
|
846 |     T: JsonSchema + Serialize + Send + Sync + 'static,
|                     --------- required by this bound in `dropshot::handler::HttpResponseOkObject`
```
After:
```console
error[E0277]: the trait bound `Ret: serde::ser::Serialize` is not satisfied
--> $DIR/bad_endpoint6.rs:22:8
|
22  |     Ok(HttpResponseOkObject(Ret { "Oxide".to_string(), 0x1de }))
| …
```
=> Hide line numbers in $WORKSPACE errors

src/normalize.rs, src/tests.rs
Updates to recognize the library paths introduced in https://github.com/rust-lang/rust/pull/73265.
- Before: */toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/net/ip.rs*
- After: */toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/net/ip.rs*
=> Recognize new standard library directory structure

build.rs, src/cargo.rs, src/lib.rs
Closes #61.
Tested with `cargo test --target x86_64-unknown-linux-gnu` inside a crate that has `[build] target = "thumbv7m-none-eabi"` in .cargo/config.
=> Propagate --target flag from cargo test invocation

src/dependencies.rs
It seems like we are ignoring certain fields from `patch` blocks from the workspace .toml
According to the [cargo docs](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section) each patch line has the same spec as a normal dependency line (with fields like version, registry, etc.)
This change captures the unused fields and serializes them to avoid Cargo issues during test runs
=> Ignored patch fields leads to Cargo issues

src/cargo.rs
At diem/diem we use sccache to speed up our builds in CI.
Sccache tracks CARGO_* environment variables, but not CARGO itself.   I think it's an open question as to what is a consistent and correct approach to hand all environment variables, who's answer will involve rustc build dep files, but I think CARGO locations could and probably should be ignored.
HISTORY:
1. We were using circleci and migrating to gha actions.
2. Circleci environment and gha environment differed in that cargo locations (long story related to docker handling in both environments)
3. Only trybuld test would fail when using a binary pulled from the cache with incorrect embedded cargo location, a race condition between the two CIs during the transition.
Since cargo always sets the CARGO env it should be safe to move …
=> [sccache compat] work well with sccache

src/normalize.rs
This is required as the path is different for every user.
Old behavior:
```
::: /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/parity-scale-codec-2.2.0/src/codec.rs:284:18
|
284 |     fn decode<I: Input>(input: &mut I) -> Result<Self, Error>;
|                  ----- required by this bound in `pallet::_::_parity_scale_codec::Decode::decode`
```
New behavior:
```
::: $CARGO_REGISTRY/github.com-1ecc6299db9ec823/parity-scale-codec-2.2.0/src/codec.rs
|
|     fn decode<I: Input>(input: &mut I) -> Result<Self, Error>;
|                  ----- required by this bound in `pallet::_::_parity_scale_codec::Decode::decode`
```
=> Replace path to cargo registry with normalized path

build.rs
When `--target` flag is passed, cargo does not pass `RUSTFLAGS` to rustc when building proc-macro and build script even if the host and target triples are the same. Therefore, if we always pass `--target` to cargo, tools such as coverage that require `RUSTFLAGS` do not work for tests run by trybuild.
To avoid that problem, this patch change to not pass `--target` to cargo if we know that it has not been passed.
Cargo does not have a way to tell the build script whether `--target` has been passed or not, so we use the following heuristic:
- The host and target triples are the same.
- And `RUSTFLAGS` is available when *building* the build script.
Note that the second is when building, not when running. This is due to:
- After rust-lang/cargo#9601, cargo does not pass `RUSTFLAGS` to the …
=> Do not pass --target if user is not using --target

build.rs, src/lib.rs
Unfortunately, currently, it seems there is no heuristic that can handle this well...
So at the moment, only approaches that "require the user to explicitly specify" such as environment variables and cfg seem to work.
This PR uses an approach that exposes a cfg to always treat the target as host.
In the future, once https://github.com/rust-lang/cargo/pull/9532 merged, we can support auto-detection of this.
Closes #122
=> Add cfg to always treat target as host

src/tests.rs
Before:
```console
thread 'normalize::tests::test_basic' panicked at 'assertion failed: `(left == right)`
left: `"\nerror: `self` parameter is only allowed in associated functions\n  --> $DIR/error.rs:11:23\n   |\n11 | async fn bad_endpoint(self) -> Result<HttpResponseOkObject<()>, HttpError> {\n   |                       ^^^^ not semantically valid as function parameter\n"`,
right: `"\nerror: self parameter is only allowed in associated functions\n  --> $DIR/error.rs:11:23\n   |\n11 | async fn bad_endpoint(self) -> Result<HttpResponseOkObject<()>, HttpError> {\n   |                       ^^^^ not semantically valid as function parameter\n"`', src/tests.rs:24:1
```
After:
```console
thread 'normalize::tests::test_basic' panicked at '
ACTUAL: "
error: `self` parameter is only allowed in …
```
=> Improve assertion failure messages in test suite

src/cargo.rs, src/dependencies.rs, src/directory.rs, src/lib.rs, src/normalize.rs, src/path.rs, src/run.rs, src/tests.rs
Currently this is just a simple wrapper, but I'll be using it in an upcoming PR to guarantee that paths which are known to represent directories are always stored with a trailing `/`.
This invariant will be necessary during normalization so that for example with workspace=`/path/to` and source_dir=`/path/to/thing`, we do not substitute `/path/to/thing_macros/file.rs` to `$DIR_macros/file.rs` but instead correctly to `$WORKSPACE/thing_macros/file.rs`.
=> Wrap directory paths in a Directory type

src/directory.rs, src/normalize.rs
Follow-up to #129. For example in the case of workspace=`/path/to` and source_dir=`/path/to/thing`, we need to not substitute `/path/to/thing_macros/file.rs` to `$DIR_macros/file.rs` but instead correctly to `$WORKSPACE/thing_macros/file.rs`.
=> Prevent partial matching of source dir

src/normalize.rs, src/run.rs, src/tests.rs
Closes #142.
**Before:**
```console
--> $WORKSPACE/target/debug/build/uniffi_uitests-6472345683e61af2/out/counter.uniffi.rs
```
**After:**
```console
--> $OUT_DIR[uniffi_uitests]/counter.uniffi.rs
```
=> Normalize paths under Cargo out directory

src/cargo.rs, src/run.rs
This PR switches to getting rustc's diagnostics message through Cargo's "JSON messages" functionality, which is described in https://doc.rust-lang.org/1.59.0/cargo/reference/external-tools.html#json-messages.
This doesn't immediately offer an improvement, but this is a necessary step to leveraging Cargo's new `--keep-going` flag to build all the ui test inputs simultaneously instead of one after the other, which will be an enormous speed improvement. Without JSON messages, tests which are compiled simultaneously would end up interleaving diagnostics in a way that makes it impossible to separate and attribute each diagnostic to which input file's build it relates to.
See https://github.com/rust-lang/cargo/pull/10383 &amp; https://github.com/rust-lang/cargo/issues/10496 for more on …
=> Obtain rendered diagnostics through `--message-format=json`

src/cargo.rs, src/run.rs
This will allow conditionally using https://github.com/rust-lang/cargo/pull/10383 on toolchains that support it.
Supersedes #159, since this approach is going to have lower overhead in typical usage. #159 takes 450ms on the first `cargo test` run and 10ms on subsequent runs, whereas #160 takes 20ms on all runs.
Closes #159.
=> Add logic to check for --keep-going support

src/run.rs
Without this annotation, the main file generated by trybuild will always raise a warning/error on the respective setting for these compiler lints.
Explicitly allowing it here should have the net result of letting tests written using trybuild handle just like any other test in an environment with that lint set, and otherwise not make a difference.
=> Explicitly allow unused crate dependencies and missing docs

src/run.rs
This is necessary for eventually building multiple test cases with a single Cargo invocation (producing multiple ParsedOutput from a single Command). ExitStatus isn't directly constructible from outside the standard library, but we'll be able to tell whether each test case build succeeded a different way.
=> Replace ExitStatus with a just a `success: bool`

src/run.rs
=> Fail test on creating any new stderr files

src/cargo.rs, src/directory.rs, src/run.rs
In addition to #176, this is also needed in order for directly running an integration test binary without cargo to work (#14).
=> Search for Cargo.toml if CARGO_MANIFEST_DIR not set

src/expand.rs
Something like `t.compile_fail("foo.rs"); t.pass("foo.rs");` is probably a copy&ndash;paste error, not intentional.
=> Only do overriding of pass/fail status for tests expanded from glob

src/dependencies.rs, src/error.rs, src/run.rs
`unwrap_or_default()` is unhelpful here because it'll return a `Manifest` containing package.name="". As currently implemented, that screws up this line:
https://github.com/dtolnay/trybuild/blob/bce5f95b2ebedec3915dd71f8e426dbf8d72a4cd/src/run.rs#L153
because it ends up with `--crate-name -tests` getting passed to Cargo:
```console
running 1 test
error: Found argument '-t' which wasn't expected, or isn't valid in this context
If you tried to supply `-t` as a value rather than a flag, use `-- -t`
USAGE:
cargo check [OPTIONS]
For more information try --help
test compile_fail ... FAILED
```
Even if we fix that, the generated Cargo.toml needs to list the original library under `[dependencies]`, which it can't do unless we have a package name for it.
=> Report error from parsing Cargo.toml

src/normalize.rs, tests/test.rs, tests/ui/normalize_and_x_others.rs, tests/ui/normalize_and_x_others.stderr
This solves a major pain point for me; I have many features that add trait implementations. As such the exact number varies and that makes matching this error message very painful.
=> Normalize "and x others"

src/cargo.rs, src/run.rs
=> Recognize when the current package has no lib target

src/normalize.rs, src/tests.rs
=> Delete 'full type name' notes

src/normalize.rs
I am thinking of switching to normalizing each JSON message in isolation and then concatenating them, instead of concatenating all the JSON messages and normalizing all together.
This PR avoids the situation of "but what if those Vec are different length" when joining already normalized diagnostics.
=> Store normalization variations in array

src/cargo.rs
This works around https://github.com/rust-lang/rust/issues/106571. However this might be the right choice anyway for trybuild. I'll think about whether to remove it once the rustc bug is gone.
=> Turn off incremental compilation

src/cargo.rs, src/run.rs
Or to put it another way, do not assume that the project's `target/tests/target/` is ours to use as we wish.
Empirically, this is sufficient on its own to resolve
https://github.com/eupn/macrotest/issues/83
https://github.com/dtolnay/trybuild/issues/218
(I don't know precisely what the difference is between trybuild's and mcarotest's build invocations.  It is possible that it would be better for cargo to be able to cache both in the target directory, but I think we should use a namespaced directory, regardless.)
I will be submitting a similar merge request for macrotest, which, likewise, is sufficient on its own to resolve the problem I was experiencing.  I think these changes should be made to both packages.
=> Use subdirectory within target/tests/

src/normalize.rs, src/tests.rs
Fixed normalization of paths in form:
`/rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/core/src/fmt/mod.rs:786:1`
=> Fix normalization of rust lib path for some cases

src/path.rs, src/run.rs
According to https://doc.rust-lang.org/1.67.0/cargo/reference/config.html#hierarchical-structure config.toml is the preferred form, and is supported since Rust 1.39 whereas trybuild's current oldest supported compiler is 1.45.
=> Rename .cargo/config to the preferred form .cargo/config.toml

src/normalize.rs, src/tests.rs
Cargo's sparse protocol: https://blog.rust-lang.org/inside-rust/2023/01/30/cargo-sparse-protocol.html
Has `index.crates.io-` rather than `github.com-`.
=> Add `$CARGO` normalization for new sparse protocol `/registry/src/index.crates.io-`

src/run.rs
`warn(unused_crate_dependencies)` was introduced in Rust 1.45 by https://github.com/rust-lang/rust/pull/72342. At the time, trybuild supported rustc 1.36+. These days it requires rustc 1.56+.
=> No more need for unknown_lints suppression

src/cargo.rs
As soon as https://github.com/rust-lang/cargo/pull/12568 is present in nightly.
=> Stabilize Cargo's `--keep-going` flag

src/flock.rs
Warning is new in nightly-2024-01-06 due to https://github.com/rust-lang/rust/pull/118297.
```console
warning: field `0` is never read
--> src/flock.rs:22:12
|
22 |     Locked(MutexGuard<'static, ()>),
|     ------ ^^^^^^^^^^^^^^^^^^^^^^^
|     |
|     field in this variant
|
= note: `#[warn(dead_code)]` on by default
help: consider changing the field to be of unit type to suppress this warning while preserving the field numbering, or remove the field
|
22 |     Locked(()),
|            ~~
```
=> Work around dead_code warning in flock implementation

src/normalize.rs, src/tests/gated-feature.rs
Since https://github.com/rust-lang/rust/pull/119088, rustc is putting the compiler build date into diagnostics, which is inappropriate for ui tests.
```console
error[E0658]: `#[used(linker)]` is currently unstable
--> tests/ui/used-linker.rs:6:5
|
6 |     #![used(linker)]
|     ^^^^^^^^^^^^^^^^
|
= note: see issue #93798 <https://github.com/rust-lang/rust/issues/93798> for more information
= help: add `#![feature(used_with_arg)]` to the crate attributes to enable
= note: this compiler was built on 2024-01-13; consider upgrading it if it is out of date
```
=> Normalize compiler build date note

build.rs
Otherwise, if `cargo test --lib` has previously succeeded, and a new test is dropped into src/tests without touching any pre-existing source file in the crate, then another `cargo test --lib` will not perform a rebuild and the new test is not picked up by automod.
https://github.com/dtolnay/trybuild/blob/840b110e7593310995d398db995041ba500cb5d7/src/tests.rs#L34-L36
=> Force rebuild on new files in tests directory

.github/workflows/ci.yml, Cargo.toml, src/dependencies.rs, src/error.rs, src/run.rs
=> Drop basic-toml in favor of more widely used toml crate

Cargo.toml, README.md
Replacing basic-toml crate in dtolnay/trybuild#239 raised MSRV for trybuild to 1.67 (toml_datetime specifies this minimum), but CI workflow was updated to 1.70 in that PR, so this patch raises MSRV to 1.70 instead.
A reference to even older MSRV in the README is removed entirely since this information lives in Cargo.toml as of Rust 1.56.
=> Update MSRV to reflect changes to dependencies

src/env.rs, src/flock.rs, src/lib.rs, src/manifest.rs, src/normalize.rs, src/run.rs
=> Resolve new clippy lints from Rust 1.57 through 1.70

Cargo.toml, src/flock.rs, src/term.rs
Our MSRV is now 1.70, so we can use `std::sync::OnceLock` instead of `once_cell::sync::OnceCell`.
=> Remove dependency on once_cell

src/flock.rs
The other OnceLock from #266 can go away too, but requires some `termcolor` changes first.
=> Remove OnceLock around intra-process lock's mutex

src/normalize.rs, src/tests/and-others-verbose.rs
The `--verbose` flag from #270 was intended to control type name shortening (#269: _"consider using \`--verbose\` to print the full type name to the console"_). But it also changes the behavior of the kind of errors from #198. With `--verbose`, instead of _"and $N others"_ rustc will print the full list of other trait impls, regardless of how many.
This PR normalizes the effect of `--verbose` on such diagnostics so that they better resemble what a real user would see, and to reduce churn in ui tests containing long impl lists.
=> Normalize the effect of `--verbose` on '$N others' diagnostic

src/cargo.rs, src/manifest.rs, src/run.rs, src/rustflags.rs
The `--verbose` flag from #270 is not being applied consistently in all environments because of interference with the RUSTFLAGS environment variable, which takes precedence (https://doc.rust-lang.org/1.79.0/cargo/reference/config.html#buildrustflags).
This PR consolidates all 3 previously used sources of flags (`.cargo/config.toml`, `$RUSTFLAGS`, `--config=build.rustflags`) into just using `--config=build.rustflags`.
=> Combine all rustflags into cargo `--config` arg

src/dependencies.rs
If in a crate `Cargo.toml` there is a dependency with `default-features = true` and `workspace = true`
If in the workspace `Cargo.toml` the depended crate is written with `default-features = false`
Then we must serialize the `default-features = true` when doing the manifest for the test.
Otherwise the test will run with `default-features = false` which is not the expected behavior.
=> Fix default features in dependency

README.md, src/lib.rs
I've stumbled on a problem where my compile error messages locally differed from the output on CI. This caused trybuild tests not to pass on CI, but pass locally:
Helpful people on Rust Zulip/Discord suggested that the difference was that I didn't have `rust-src` installed on CI. And that appeared to be the cause.
I propose to add this caveat to the documentation so that people don't stumble on this again.
=> Warn about the `rust-src` component footgun in the docs

src/path.rs, src/run.rs
Closes #299. The filepaths that appear in rustc's `--message-format=json` JSON output can be inconsistent with the corresponding paths for the same test file produced by `project.source_dir.join(&t.test.path)`.
=> Canonicalize paths used as map keys

src/normalize.rs, src/tests/multiline-note.rs
**Before:**
```console
error[E0038]: the trait `MyTrait` is not dyn compatible
--> src/main.rs:8:12
|
8 |     let _: &dyn MyTrait;
|            ^^^^^^^^^^^^ `MyTrait` is not dyn compatible
|
note: for a trait to be dyn compatible it needs to allow building a vtable
for more information, visit <https://doc.rust-lang.org/reference/items/traits.html#object-safety>
--> $RUST/core/src/hash/mod.rs
|
|     fn hash<H: Hasher>(&self, state: &mut H);
|        ^^^^ ...because method `hash` has generic type parameters
|
::: src/main.rs:3:7
|
3   | trait MyTrait: Hash {
|       ------- this trait is not dyn compatible...
= help: consider moving `hash` to another trait
```
**After:**
```console
error[E0038]: the trait `MyTrait` is not dyn compatible
--> src/main.rs:8:12
|
8 |     let _: &dyn MyTrait;
| …
```
=> Fix unindentation of multiline note

src/rustflags.rs
Workaround for #283, specifically for the case of coverage with `cargo llvm-cov`.
From what I understand, since trybuild 1.0.97, RUSTFLAGS are blocked from the environment. This has the effect of breaking `cargo-llvm-cov` integration with trybuild tests, because it sets `-C instrument-coverage` in `RUSTFLAGS`.
As a result, we stopped getting coverage of PyO3 proc macro cases covered by UI tests (e.g. error cases which cause a compile failure). We'd been getting lucky that our MSRV job was producing that coverage against trybuild 1.0.89, but that won't last forever.
This PR is an attempt to restore that functionality. It's a bit crude, and I'm happy to rework or edit this to a design which you'd prefer. I'm more invested in getting this working again than I am in any particular …
=> support passing `-C instrument-coverage` in RUSTFLAGS

src/cargo.rs
```console
warning: call to `set_readonly` with argument `false`
--> src/cargo.rs:83:17
|
83 |                 permissions.set_readonly(false);
|                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: on Unix platforms this results in the file being world writable
= help: you can set the desired permissions using `PermissionsExt`. For more information, see
https://doc.rust-lang.org/std/os/unix/fs/trait.PermissionsExt.html
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#permissions_set_readonly_false
= note: `-W clippy::permissions-set-readonly-false` implied by `-W clippy::all`
= help: to override `-W clippy::all` add `#[allow(clippy::permissions_set_readonly_false)]`
```
=> Fix permissions_set_readonly_false warning
