dtolnay/trybuild

- src/dependencies.rs
- src/run.rs
> Allow access to dependencies in addition to dev-dependencies

- .gitignore
- src/run.rs
> Write gitignore file in the wip directory

- src/features.rs
closes #9 
Fixes the error for me on Windows.
> fix feature flag detection on Windows

- src/normalize.rs
Maybe fixes #66.
@robjtede I don't have access to Windows so would you be able to try whether this makes your test work?
> Normalize Windows path separator

- src/normalize.rs
If the host has `rustup component add rust-lib` installed, rustc will occasionally produce error messages containing paths to those files. Normalize those absolute paths so they are more transferable across hosts.
```console
error[E0599]: no method named `quote_into_iter` found for struct `std::net::Ipv4Addr` in the current scope
--> $DIR/not-repeatable.rs:6:13
|
6  |     let _ = quote! { #(#ip)* };
|             ^^^^^^^^^^^^^^^^^^ method not found in `std::net::Ipv4Addr`
|
::: $RUST/src/libstd/net/ip.rs:83:1
|
83 | pub struct Ipv4Addr {
| -------------------
| |
| doesn't satisfy `std::net::Ipv4Addr: quote::to_tokens::ToTokens`
```
> Normalize paths inside of local rust-lib component

- src/lib.rs
- src/run.rs
This is a Clippy false positive. https://github.com/rust-lang/rust-clippy/issues/5991
> Note clippy needless_collect false positive locally

- src/normalize.rs
> Replace paths using case-insensitive comparison

- src/cargo.rs
- src/run.rs
> Copy workspace's Cargo.lock if present

- src/cargo.rs
- src/normalize.rs
- src/run.rs
- src/tests.rs
> Normalize paths for path dependencies

- src/flock.rs
- src/lib.rs
- src/run.rs
> Prevent concurrent test runs from clashing on project directory

- README.md
Add documentation stating how to test just a single file. I had to go looking through closed issues to find this.
> Document #23

- src/normalize.rs
- src/tests.rs
> Fix unexpected dir substitution in url

- src/dependencies.rs
- src/manifest.rs
- src/run.rs
See https://github.com/dtolnay/trybuild/pull/146#issuecomment-1024565428.
> Propagate `package.resolver` into generated Cargo.toml

- src/tests.rs
> Add test case that reproduces issue 147

- src/normalize.rs
- src/tests.rs
> Normalize backslashes in path after ^^^^ message

- src/cargo.rs
To be reusable for an upcoming PR.
> Extract CARGO_TARGET_DIR logic

- src/run.rs
This should have no immediate effect except maybe in very strange cases involving forged Spans. However, this is a necessary step toward adopting Cargo's new `--keep-going` because we'll be building all the input files simultaneously, and will need to use src paths to separate out which diagnostics are coming from which test cases.
> Only consider diagnostics located in the current src path

- src/run.rs
Necessary for eventually building multiple test cases in parallel by a single Cargo invocation.
> Infer success from presence of 'error' diagnostic

- src/run.rs
Working toward compiling multiple test cases in parallel by a single Cargo invocation.
> Parse diagnostics across multiple files into a map

- src/dependencies.rs
- src/error.rs
- src/run.rs
> Read crate name from manifest instead of CARGO_PKG_NAME env

- src/expand.rs
- src/lib.rs
- src/run.rs
This logic is going to get a little more elaborate as part of #174.
> Move glob expansion to new module

- src/expand.rs
> Factor out a data structure for building a set of expanded test

- src/expand.rs
> Deduplicate glob-expanded tests by path

- src/dependencies.rs
- src/manifest.rs
- src/run.rs
> Support dependency inheritance from workspace manifest

- src/normalize.rs
- src/tests.rs
> Normalize left margin of error output

- src/run.rs
> Fix "optional dependency is not included in any features"

- src/dependencies.rs
- src/run.rs
https://github.com/dtolnay/trybuild/issues/171#issuecomment-1269368633
> Skip "dep:" feature for non-optional dev-dependencies

- src/run.rs
This might no longer be necessary after https://github.com/rust-lang/rust/issues/106571 is fixed. Normally rustc would filter duplicates itself and I think this is a short-lived bug.
> Discard duplicate json messages from rustc

- src/flock.rs
This shows up in panic messages.
> Add thread name for flock thread

- src/cargo.rs
- src/dependencies.rs
- src/diff.rs
- src/directory.rs
- src/env.rs
- src/error.rs
- src/features.rs
- src/flock.rs
- src/inherit.rs
- src/manifest.rs
- src/normalize.rs
- src/run.rs
- src/rustflags.rs
- src/term.rs
This gives better dead code linting.
> Reduce visibility of items that are not publicly accessible

- src/cargo.rs
> Disable long typename shortening in diagnostics

- build.rs
- src/cargo.rs
See https://github.com/dtolnay/rustversion/pull/51.
> Support OUT_DIR located in `\\?\` path on Windows

- src/dependencies.rs
- src/run.rs
Fixes https://github.com/dtolnay/trybuild/pull/282#issuecomment-2260491977.
> Keep track of whether manifest overrides workspace dependency's default-features

- README.md
- src/lib.rs
This is what I use in my crates. For example https://github.com/dtolnay/anyhow/commit/369af51a4c4533c924356377cc95ff11baf53731.
> Recommend rust-toolchain.toml file

- Cargo.toml
Release notes:
https://github.com/toml-rs/toml/blob/toml-v0.9.0/crates/toml/CHANGELOG.md#090---2025-07-08
> Update to toml 0.9

- src/normalize.rs
- src/tests/right-aligned-line-number.rs
https://github.com/rust-lang/rust/pull/144609
> Recognize right aligned line numbers
